# Generated by Django 4.0.3 on 2022-03-11 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image_url', models.URLField()),
                ('description', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('googleId', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('image_url', models.URLField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('favourite_artists', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='music_mates.artist')),
            ],
        ),
    ]
