# Generated by Django 4.0.3 on 2022-03-11 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music_mates', '0002_rename_googleid_user_google_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favourite_artists',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='artist', to='music_mates.artist'),
        ),
    ]
