# Generated by Django 4.0.3 on 2022-03-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_mates', '0003_alter_user_favourite_artists'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favourite_artists',
        ),
        migrations.AddField(
            model_name='user',
            name='favourite_artists',
            field=models.ManyToManyField(to='music_mates.artist'),
        ),
    ]
