# Generated by Django 4.0.3 on 2022-03-11 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_mates', '0004_remove_user_favourite_artists_user_favourite_artists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favourite_artists',
            field=models.ManyToManyField(related_name='favourite_users', to='music_mates.artist'),
        ),
    ]
